### PR TITLE
	modified:   classes/class-ventus-shortcode.php

### PR DESCRIPTION
**Pull request by marcoGH9**
modified:   classes/class-ventus-widget.php
	modified:   readme.txt
	modified:   weather-map.php

### CODE REVIEW

**Comment by marcoGH9** [comment]
Italian language file updated

**Comment by marcoGH9** [comment]
I hope I have also fixed the part relating to the model of the weather forecast.
Maybe the language part needs to be changed...

**Review by davidmatthew-ie — APPROVED** [review]
Hi Marco, thanks for your updates. Before I merge your changes, can you revert the lat and lon values to what they were and just adjust the indentation of some of your code additions (e.g. where you've added $model)? Really great first commit! Great work on adding an Italian translation too, really nice to have that.

**Comment by marcoGH9** [comment]
I fixed lat and lon
I fixed the alignment

**Pull request merged**
